/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AccountsBooksListRelationFilter } from "../../accountsBooks/base/AccountsBooksListRelationFilter";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { ClientsBooksListRelationFilter } from "../../clientsBooks/base/ClientsBooksListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { TextsListRelationFilter } from "../../texts/base/TextsListRelationFilter";

@InputType()
class BooksWhereInput {
  @ApiProperty({
    required: false,
    type: () => AccountsBooksListRelationFilter,
  })
  @ValidateNested()
  @Type(() => AccountsBooksListRelationFilter)
  @IsOptional()
  @Field(() => AccountsBooksListRelationFilter, {
    nullable: true,
  })
  accountsBooksItems?: AccountsBooksListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => ClientsBooksListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ClientsBooksListRelationFilter)
  @IsOptional()
  @Field(() => ClientsBooksListRelationFilter, {
    nullable: true,
  })
  clientsBooksItems?: ClientsBooksListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => TextsListRelationFilter,
  })
  @ValidateNested()
  @Type(() => TextsListRelationFilter)
  @IsOptional()
  @Field(() => TextsListRelationFilter, {
    nullable: true,
  })
  textsItems?: TextsListRelationFilter;
}

export { BooksWhereInput as BooksWhereInput };
