/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AccountsBooksListRelationFilter } from "../../accountsBooks/base/AccountsBooksListRelationFilter";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { OrdersListRelationFilter } from "../../orders/base/OrdersListRelationFilter";
import { PhonesWhereUniqueInput } from "../../phones/base/PhonesWhereUniqueInput";

@InputType()
class AccountsWhereInput {
  @ApiProperty({
    required: false,
    type: () => AccountsBooksListRelationFilter,
  })
  @ValidateNested()
  @Type(() => AccountsBooksListRelationFilter)
  @IsOptional()
  @Field(() => AccountsBooksListRelationFilter, {
    nullable: true,
  })
  accountsBooksItems?: AccountsBooksListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  accountsName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  followers?: IntNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => OrdersListRelationFilter,
  })
  @ValidateNested()
  @Type(() => OrdersListRelationFilter)
  @IsOptional()
  @Field(() => OrdersListRelationFilter, {
    nullable: true,
  })
  ordersItems?: OrdersListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => PhonesWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PhonesWhereUniqueInput)
  @IsOptional()
  @Field(() => PhonesWhereUniqueInput, {
    nullable: true,
  })
  phone?: PhonesWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  profilePicture?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  totalLikes?: IntNullableFilter;
}

export { AccountsWhereInput as AccountsWhereInput };
