/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AccountsBooksCreateNestedManyWithoutAccountsItemsInput } from "./AccountsBooksCreateNestedManyWithoutAccountsItemsInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsInt,
  Min,
  Max,
} from "class-validator";
import { Type } from "class-transformer";
import { OrdersCreateNestedManyWithoutAccountsItemsInput } from "./OrdersCreateNestedManyWithoutAccountsItemsInput";
import { PhonesWhereUniqueInput } from "../../phones/base/PhonesWhereUniqueInput";

@InputType()
class AccountsCreateInput {
  @ApiProperty({
    required: false,
    type: () => AccountsBooksCreateNestedManyWithoutAccountsItemsInput,
  })
  @ValidateNested()
  @Type(() => AccountsBooksCreateNestedManyWithoutAccountsItemsInput)
  @IsOptional()
  @Field(() => AccountsBooksCreateNestedManyWithoutAccountsItemsInput, {
    nullable: true,
  })
  accountsBooksItems?: AccountsBooksCreateNestedManyWithoutAccountsItemsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  accountsName?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  followers?: number | null;

  @ApiProperty({
    required: false,
    type: () => OrdersCreateNestedManyWithoutAccountsItemsInput,
  })
  @ValidateNested()
  @Type(() => OrdersCreateNestedManyWithoutAccountsItemsInput)
  @IsOptional()
  @Field(() => OrdersCreateNestedManyWithoutAccountsItemsInput, {
    nullable: true,
  })
  ordersItems?: OrdersCreateNestedManyWithoutAccountsItemsInput;

  @ApiProperty({
    required: false,
    type: () => PhonesWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PhonesWhereUniqueInput)
  @IsOptional()
  @Field(() => PhonesWhereUniqueInput, {
    nullable: true,
  })
  phone?: PhonesWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  profilePicture?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  totalLikes?: number | null;
}

export { AccountsCreateInput as AccountsCreateInput };
