/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { TextsLabelsService } from "../textsLabels.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TextsLabelsCreateInput } from "./TextsLabelsCreateInput";
import { TextsLabels } from "./TextsLabels";
import { TextsLabelsFindManyArgs } from "./TextsLabelsFindManyArgs";
import { TextsLabelsWhereUniqueInput } from "./TextsLabelsWhereUniqueInput";
import { TextsLabelsUpdateInput } from "./TextsLabelsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class TextsLabelsControllerBase {
  constructor(
    protected readonly service: TextsLabelsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TextsLabels })
  @nestAccessControl.UseRoles({
    resource: "TextsLabels",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createTextsLabels(
    @common.Body() data: TextsLabelsCreateInput
  ): Promise<TextsLabels> {
    return await this.service.createTextsLabels({
      data: {
        ...data,

        label: data.label
          ? {
              connect: data.label,
            }
          : undefined,

        text: data.text
          ? {
              connect: data.text,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,

        label: {
          select: {
            id: true,
          },
        },

        text: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [TextsLabels] })
  @ApiNestedQuery(TextsLabelsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "TextsLabels",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async textsLabelsItems(
    @common.Req() request: Request
  ): Promise<TextsLabels[]> {
    const args = plainToClass(TextsLabelsFindManyArgs, request.query);
    return this.service.textsLabelsItems({
      ...args,
      select: {
        createdAt: true,
        id: true,

        label: {
          select: {
            id: true,
          },
        },

        text: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TextsLabels })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TextsLabels",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async textsLabels(
    @common.Param() params: TextsLabelsWhereUniqueInput
  ): Promise<TextsLabels | null> {
    const result = await this.service.textsLabels({
      where: params,
      select: {
        createdAt: true,
        id: true,

        label: {
          select: {
            id: true,
          },
        },

        text: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TextsLabels })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TextsLabels",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateTextsLabels(
    @common.Param() params: TextsLabelsWhereUniqueInput,
    @common.Body() data: TextsLabelsUpdateInput
  ): Promise<TextsLabels | null> {
    try {
      return await this.service.updateTextsLabels({
        where: params,
        data: {
          ...data,

          label: data.label
            ? {
                connect: data.label,
              }
            : undefined,

          text: data.text
            ? {
                connect: data.text,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,

          label: {
            select: {
              id: true,
            },
          },

          text: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TextsLabels })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TextsLabels",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteTextsLabels(
    @common.Param() params: TextsLabelsWhereUniqueInput
  ): Promise<TextsLabels | null> {
    try {
      return await this.service.deleteTextsLabels({
        where: params,
        select: {
          createdAt: true,
          id: true,

          label: {
            select: {
              id: true,
            },
          },

          text: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
