/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BooksWhereUniqueInput } from "../../books/base/BooksWhereUniqueInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { CaptionsUpdateManyWithoutTextsItemsInput } from "./CaptionsUpdateManyWithoutTextsItemsInput";
import { OrdersUpdateManyWithoutTextsItemsInput } from "./OrdersUpdateManyWithoutTextsItemsInput";
import { TextsHashtagsUpdateManyWithoutTextsItemsInput } from "./TextsHashtagsUpdateManyWithoutTextsItemsInput";
import { TextsLabelsUpdateManyWithoutTextsItemsInput } from "./TextsLabelsUpdateManyWithoutTextsItemsInput";

@InputType()
class TextsUpdateInput {
  @ApiProperty({
    required: false,
    type: () => BooksWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => BooksWhereUniqueInput)
  @IsOptional()
  @Field(() => BooksWhereUniqueInput, {
    nullable: true,
  })
  book?: BooksWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => CaptionsUpdateManyWithoutTextsItemsInput,
  })
  @ValidateNested()
  @Type(() => CaptionsUpdateManyWithoutTextsItemsInput)
  @IsOptional()
  @Field(() => CaptionsUpdateManyWithoutTextsItemsInput, {
    nullable: true,
  })
  captionsItems?: CaptionsUpdateManyWithoutTextsItemsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => OrdersUpdateManyWithoutTextsItemsInput,
  })
  @ValidateNested()
  @Type(() => OrdersUpdateManyWithoutTextsItemsInput)
  @IsOptional()
  @Field(() => OrdersUpdateManyWithoutTextsItemsInput, {
    nullable: true,
  })
  ordersItems?: OrdersUpdateManyWithoutTextsItemsInput;

  @ApiProperty({
    required: false,
    type: () => TextsHashtagsUpdateManyWithoutTextsItemsInput,
  })
  @ValidateNested()
  @Type(() => TextsHashtagsUpdateManyWithoutTextsItemsInput)
  @IsOptional()
  @Field(() => TextsHashtagsUpdateManyWithoutTextsItemsInput, {
    nullable: true,
  })
  textsHashtagsItems?: TextsHashtagsUpdateManyWithoutTextsItemsInput;

  @ApiProperty({
    required: false,
    type: () => TextsLabelsUpdateManyWithoutTextsItemsInput,
  })
  @ValidateNested()
  @Type(() => TextsLabelsUpdateManyWithoutTextsItemsInput)
  @IsOptional()
  @Field(() => TextsLabelsUpdateManyWithoutTextsItemsInput, {
    nullable: true,
  })
  textsLabelsItems?: TextsLabelsUpdateManyWithoutTextsItemsInput;
}

export { TextsUpdateInput as TextsUpdateInput };
