/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BooksWhereUniqueInput } from "../../books/base/BooksWhereUniqueInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { CaptionsListRelationFilter } from "../../captions/base/CaptionsListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { OrdersListRelationFilter } from "../../orders/base/OrdersListRelationFilter";
import { TextsHashtagsListRelationFilter } from "../../textsHashtags/base/TextsHashtagsListRelationFilter";
import { TextsLabelsListRelationFilter } from "../../textsLabels/base/TextsLabelsListRelationFilter";

@InputType()
class TextsWhereInput {
  @ApiProperty({
    required: false,
    type: () => BooksWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => BooksWhereUniqueInput)
  @IsOptional()
  @Field(() => BooksWhereUniqueInput, {
    nullable: true,
  })
  book?: BooksWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => CaptionsListRelationFilter,
  })
  @ValidateNested()
  @Type(() => CaptionsListRelationFilter)
  @IsOptional()
  @Field(() => CaptionsListRelationFilter, {
    nullable: true,
  })
  captionsItems?: CaptionsListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => OrdersListRelationFilter,
  })
  @ValidateNested()
  @Type(() => OrdersListRelationFilter)
  @IsOptional()
  @Field(() => OrdersListRelationFilter, {
    nullable: true,
  })
  ordersItems?: OrdersListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => TextsHashtagsListRelationFilter,
  })
  @ValidateNested()
  @Type(() => TextsHashtagsListRelationFilter)
  @IsOptional()
  @Field(() => TextsHashtagsListRelationFilter, {
    nullable: true,
  })
  textsHashtagsItems?: TextsHashtagsListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => TextsLabelsListRelationFilter,
  })
  @ValidateNested()
  @Type(() => TextsLabelsListRelationFilter)
  @IsOptional()
  @Field(() => TextsLabelsListRelationFilter, {
    nullable: true,
  })
  textsLabelsItems?: TextsLabelsListRelationFilter;
}

export { TextsWhereInput as TextsWhereInput };
