/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { VideoMetricsService } from "../videoMetrics.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { VideoMetricsCreateInput } from "./VideoMetricsCreateInput";
import { VideoMetrics } from "./VideoMetrics";
import { VideoMetricsFindManyArgs } from "./VideoMetricsFindManyArgs";
import { VideoMetricsWhereUniqueInput } from "./VideoMetricsWhereUniqueInput";
import { VideoMetricsUpdateInput } from "./VideoMetricsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class VideoMetricsControllerBase {
  constructor(
    protected readonly service: VideoMetricsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: VideoMetrics })
  @nestAccessControl.UseRoles({
    resource: "VideoMetrics",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createVideoMetrics(
    @common.Body() data: VideoMetricsCreateInput
  ): Promise<VideoMetrics> {
    return await this.service.createVideoMetrics({
      data: {
        ...data,

        order: data.order
          ? {
              connect: data.order,
            }
          : undefined,
      },
      select: {
        comments: true,
        createdAt: true,
        id: true,
        likes: true,

        order: {
          select: {
            id: true,
          },
        },

        saves: true,
        shares: true,
        updatedAt: true,
        views: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [VideoMetrics] })
  @ApiNestedQuery(VideoMetricsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "VideoMetrics",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async videoMetricsItems(
    @common.Req() request: Request
  ): Promise<VideoMetrics[]> {
    const args = plainToClass(VideoMetricsFindManyArgs, request.query);
    return this.service.videoMetricsItems({
      ...args,
      select: {
        comments: true,
        createdAt: true,
        id: true,
        likes: true,

        order: {
          select: {
            id: true,
          },
        },

        saves: true,
        shares: true,
        updatedAt: true,
        views: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: VideoMetrics })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "VideoMetrics",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async videoMetrics(
    @common.Param() params: VideoMetricsWhereUniqueInput
  ): Promise<VideoMetrics | null> {
    const result = await this.service.videoMetrics({
      where: params,
      select: {
        comments: true,
        createdAt: true,
        id: true,
        likes: true,

        order: {
          select: {
            id: true,
          },
        },

        saves: true,
        shares: true,
        updatedAt: true,
        views: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: VideoMetrics })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "VideoMetrics",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateVideoMetrics(
    @common.Param() params: VideoMetricsWhereUniqueInput,
    @common.Body() data: VideoMetricsUpdateInput
  ): Promise<VideoMetrics | null> {
    try {
      return await this.service.updateVideoMetrics({
        where: params,
        data: {
          ...data,

          order: data.order
            ? {
                connect: data.order,
              }
            : undefined,
        },
        select: {
          comments: true,
          createdAt: true,
          id: true,
          likes: true,

          order: {
            select: {
              id: true,
            },
          },

          saves: true,
          shares: true,
          updatedAt: true,
          views: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: VideoMetrics })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "VideoMetrics",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteVideoMetrics(
    @common.Param() params: VideoMetricsWhereUniqueInput
  ): Promise<VideoMetrics | null> {
    try {
      return await this.service.deleteVideoMetrics({
        where: params,
        select: {
          comments: true,
          createdAt: true,
          id: true,
          likes: true,

          order: {
            select: {
              id: true,
            },
          },

          saves: true,
          shares: true,
          updatedAt: true,
          views: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
