/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ClientsBooksService } from "../clientsBooks.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ClientsBooksCreateInput } from "./ClientsBooksCreateInput";
import { ClientsBooks } from "./ClientsBooks";
import { ClientsBooksFindManyArgs } from "./ClientsBooksFindManyArgs";
import { ClientsBooksWhereUniqueInput } from "./ClientsBooksWhereUniqueInput";
import { ClientsBooksUpdateInput } from "./ClientsBooksUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ClientsBooksControllerBase {
  constructor(
    protected readonly service: ClientsBooksService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ClientsBooks })
  @nestAccessControl.UseRoles({
    resource: "ClientsBooks",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createClientsBooks(
    @common.Body() data: ClientsBooksCreateInput
  ): Promise<ClientsBooks> {
    return await this.service.createClientsBooks({
      data: {
        ...data,

        book: data.book
          ? {
              connect: data.book,
            }
          : undefined,

        client: data.client
          ? {
              connect: data.client,
            }
          : undefined,
      },
      select: {
        book: {
          select: {
            id: true,
          },
        },

        client: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ClientsBooks] })
  @ApiNestedQuery(ClientsBooksFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ClientsBooks",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async clientsBooksItems(
    @common.Req() request: Request
  ): Promise<ClientsBooks[]> {
    const args = plainToClass(ClientsBooksFindManyArgs, request.query);
    return this.service.clientsBooksItems({
      ...args,
      select: {
        book: {
          select: {
            id: true,
          },
        },

        client: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ClientsBooks })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ClientsBooks",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async clientsBooks(
    @common.Param() params: ClientsBooksWhereUniqueInput
  ): Promise<ClientsBooks | null> {
    const result = await this.service.clientsBooks({
      where: params,
      select: {
        book: {
          select: {
            id: true,
          },
        },

        client: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ClientsBooks })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ClientsBooks",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateClientsBooks(
    @common.Param() params: ClientsBooksWhereUniqueInput,
    @common.Body() data: ClientsBooksUpdateInput
  ): Promise<ClientsBooks | null> {
    try {
      return await this.service.updateClientsBooks({
        where: params,
        data: {
          ...data,

          book: data.book
            ? {
                connect: data.book,
              }
            : undefined,

          client: data.client
            ? {
                connect: data.client,
              }
            : undefined,
        },
        select: {
          book: {
            select: {
              id: true,
            },
          },

          client: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ClientsBooks })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ClientsBooks",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteClientsBooks(
    @common.Param() params: ClientsBooksWhereUniqueInput
  ): Promise<ClientsBooks | null> {
    try {
      return await this.service.deleteClientsBooks({
        where: params,
        select: {
          book: {
            select: {
              id: true,
            },
          },

          client: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
