/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Crew } from "./Crew";
import { CrewCountArgs } from "./CrewCountArgs";
import { CrewFindManyArgs } from "./CrewFindManyArgs";
import { CrewFindUniqueArgs } from "./CrewFindUniqueArgs";
import { CreateCrewArgs } from "./CreateCrewArgs";
import { UpdateCrewArgs } from "./UpdateCrewArgs";
import { DeleteCrewArgs } from "./DeleteCrewArgs";
import { PhonesFindManyArgs } from "../../phones/base/PhonesFindManyArgs";
import { Phones } from "../../phones/base/Phones";
import { CrewService } from "../crew.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Crew)
export class CrewResolverBase {
  constructor(
    protected readonly service: CrewService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Crew",
    action: "read",
    possession: "any",
  })
  async _crewsMeta(
    @graphql.Args() args: CrewCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Crew])
  @nestAccessControl.UseRoles({
    resource: "Crew",
    action: "read",
    possession: "any",
  })
  async crews(@graphql.Args() args: CrewFindManyArgs): Promise<Crew[]> {
    return this.service.crews(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Crew, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Crew",
    action: "read",
    possession: "own",
  })
  async crew(@graphql.Args() args: CrewFindUniqueArgs): Promise<Crew | null> {
    const result = await this.service.crew(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Crew)
  @nestAccessControl.UseRoles({
    resource: "Crew",
    action: "create",
    possession: "any",
  })
  async createCrew(@graphql.Args() args: CreateCrewArgs): Promise<Crew> {
    return await this.service.createCrew({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Crew)
  @nestAccessControl.UseRoles({
    resource: "Crew",
    action: "update",
    possession: "any",
  })
  async updateCrew(@graphql.Args() args: UpdateCrewArgs): Promise<Crew | null> {
    try {
      return await this.service.updateCrew({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Crew)
  @nestAccessControl.UseRoles({
    resource: "Crew",
    action: "delete",
    possession: "any",
  })
  async deleteCrew(@graphql.Args() args: DeleteCrewArgs): Promise<Crew | null> {
    try {
      return await this.service.deleteCrew(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Phones], { name: "phonesItems" })
  @nestAccessControl.UseRoles({
    resource: "Phones",
    action: "read",
    possession: "any",
  })
  async findPhonesItems(
    @graphql.Parent() parent: Crew,
    @graphql.Args() args: PhonesFindManyArgs
  ): Promise<Phones[]> {
    const results = await this.service.findPhonesItems(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
